<a href="https://www.kaggle.com/code/puneetkoundal/nanogpt-for-hindi?scriptVersionId=212889729" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

# objective

"Building NanoGPT from Scratch for Hindi Corpus: Project 'OM'

This project involves developing a NanoGPT model from the ground up, specifically designed for processing and generating text in Hindi. The model will be trained on a Hindi corpus to ensure it captures the nuances of the language and produces coherent, contextually appropriate outputs. Named 'OM', this initiative aims to create a lightweight, efficient language model for Hindi NLP tasks.

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

ModuleNotFoundError: No module named 'numpy'

# data preparation 

In [2]:
with open('/kaggle/input/mini-hindi-corpus/combo.txt','r',encoding='utf-8') as f :
    text=f.read()

print(f"the length of chracters dataset {len(text)}")

the length of chracters dataset 4025422


In [3]:
#checking first 1000 text
print(text[:1000])


आभूषणों की निंदा करना हमारा उद्देश्य नहीं है 
 हम असहयोग का उत्पीड़न सह सकते हैं पर ललनाओं के निर्दय घातक वाक्बाणों को नहीं ओढ़ सकते 
 तो भी इतना अवश्य कहेंगे कि इस तृष्णा की पूर्ति के लिए जितना त्याग किया जाता है उसका सदुपयोग करने से महान् पद प्राप्त हो सकता है
यद्यपि हमने किसी रूप हीना महिला को आभूषणों की सजावट से रूपवती होते नहीं देखा तथापि हम यह भी मान लेते हैं कि रूप के लिए आभूषणों की उतनी ही जरूरत है जितनी घर के लिए दीपक की 
 किन्तु शारीरिक शोभा के लिए हम तन को कितना मलिन चित्त को कितना अशांत और आत्मा को कितना कलुषित बना लेते हैं इसका हमें कदाचित् ज्ञान ही नहीं होता 
 इस दीपक की ज्योति में आँखें धुँधली हो जाती हैं 
 यह चमक दमक कितनी ईर्ष्या कितने द्वेष कितनी प्रतिस्पर्धा कितनी दुश्चिंता और कितनी दुराशा का कारण है इसकी केवल कल्पना से ही रोंगटे खड़े हो जाते हैं 
 इन्हें भूषण नहीं दूषण कहना अधिक उपयुक्त है 
 नहीं तो यह कब हो सकता था कि कोई नववधू पति के घर आने के तीसरे दिन अपने पति से कहती कि मेरे पिता ने तुम्हारे पल्ले बाँध कर मुझे तो कुएँ में ढकेल दिया 
 शीतला आज अपने गाँव के ताल्लुक

In [4]:
#from uppar code we get confuse how code is calculation len of text
lines = text.split('\n')
second_row = lines[1]
print(second_row)  

आभूषणों की निंदा करना हमारा उद्देश्य नहीं है 


In [5]:
print(len(second_row))

45


In [6]:
print(text[:8])


आभूषणों


In [7]:
print(len(text[:8]))

8


In [8]:
chars=sorted(list(set(text)))
vocal_size=len(chars)
print(chars)
print(vocal_size)

['\n', '\x1a', ' ', '\xa0', '²', '×', 'ò', 'ú', 'ँ', 'ं', 'ः', 'अ', 'आ', 'इ', 'ई', 'उ', 'ऊ', 'ऋ', 'ऍ', 'ऎ', 'ए', 'ऐ', 'ऑ', 'ओ', 'औ', 'क', 'ख', 'ग', 'घ', 'ङ', 'च', 'छ', 'ज', 'झ', 'ञ', 'ट', 'ठ', 'ड', 'ढ', 'ण', 'त', 'थ', 'द', 'ध', 'न', 'ऩ', 'प', 'फ', 'ब', 'भ', 'म', 'य', 'र', 'ऱ', 'ल', 'ळ', 'व', 'श', 'ष', 'स', 'ह', '़', 'ा', 'ि', 'ी', 'ु', 'ू', 'ृ', 'ॅ', 'े', 'ै', 'ॉ', 'ो', 'ौ', '्', 'क़', 'ख़', 'ग़', 'ज़', 'ड़', 'ढ़', 'फ़', 'य़', 'ॠ', 'ॢ', '॥', '०', '१', '२', '३', '४', '५', '६', '७', '८', '९', '\u200c', '\u200d', '–', '—', '“', '”', '…']
103


# tokenization

In [9]:
# Assuming `chars` is a list of characters in your vocabulary
stoi = {ch: i for i, ch in enumerate(chars)}
itos = {i: ch for i, ch in enumerate(chars)}

# Function to encode a string into a list of integers
encode = lambda s: [stoi[c] for c in s]

# Function to decode a list of integers back into a string
decode = lambda l: ''.join(itos[i] for i in l)


In [10]:
print(encode("इन्हें भूषण नहीं दूषण कहना अधिक उपयुक्त है"))
print(decode(encode("इन्हें भूषण नहीं दूषण कहना अधिक उपयुक्त है")))

[13, 44, 74, 60, 69, 9, 2, 49, 66, 58, 39, 2, 44, 60, 64, 9, 2, 42, 66, 58, 39, 2, 25, 60, 44, 62, 2, 11, 43, 63, 25, 2, 15, 46, 51, 65, 25, 74, 40, 2, 60, 70]
इन्हें भूषण नहीं दूषण कहना अधिक उपयुक्त है


In [11]:
#did normalization work 
#let see in further labs

In [12]:
import torch 
data=torch.tensor(encode(text) , dtype=torch.long)
print(data.shape,data.dtype)
print(data[:1000])

torch.Size([4025422]) torch.int64
tensor([ 0, 12, 49, 66, 58, 39, 72,  9,  2, 25, 64,  2, 44, 63,  9, 42, 62,  2,
        25, 52, 44, 62,  2, 60, 50, 62, 52, 62,  2, 15, 42, 74, 42, 69, 57, 74,
        51,  2, 44, 60, 64,  9,  2, 60, 70,  2,  0,  2, 60, 50,  2, 11, 59, 60,
        51, 72, 27,  2, 25, 62,  2, 15, 40, 74, 46, 64, 79, 44,  2, 59, 60,  2,
        59, 25, 40, 69,  2, 60, 70,  9,  2, 46, 52,  2, 54, 54, 44, 62, 23,  9,
         2, 25, 69,  2, 44, 63, 52, 74, 42, 51,  2, 28, 62, 40, 25,  2, 56, 62,
        25, 74, 48, 62, 39, 72,  9,  2, 25, 72,  2, 44, 60, 64,  9,  2, 23, 80,
         2, 59, 25, 40, 69,  2,  0,  2, 40, 72,  2, 49, 64,  2, 13, 40, 44, 62,
         2, 11, 56, 57, 74, 51,  2, 25, 60, 69,  9, 27, 69,  2, 25, 63,  2, 13,
        59,  2, 40, 67, 58, 74, 39, 62,  2, 25, 64,  2, 46, 66, 52, 74, 40, 63,
         2, 25, 69,  2, 54, 63, 20,  2, 32, 63, 40, 44, 62,  2, 40, 74, 51, 62,
        27,  2, 25, 63, 51, 62,  2, 32, 62, 40, 62,  2, 60, 70,  2, 15, 59, 25,
      

# testsplit

In [13]:
n=int(0.9*len(data))
train_data=data[:n]
val_data=data[n:]

In [14]:
block_size=9
train_data[:block_size]

tensor([ 0, 12, 49, 66, 58, 39, 72,  9,  2])

In [15]:
x=train_data[:block_size]
y=train_data[1:block_size+1]
for t in range (block_size):
    contex=x[:t+1]
    target=y[t]
    print(f"when the input is {contex} the targer: {target}")

when the input is tensor([0]) the targer: 12
when the input is tensor([ 0, 12]) the targer: 49
when the input is tensor([ 0, 12, 49]) the targer: 66
when the input is tensor([ 0, 12, 49, 66]) the targer: 58
when the input is tensor([ 0, 12, 49, 66, 58]) the targer: 39
when the input is tensor([ 0, 12, 49, 66, 58, 39]) the targer: 72
when the input is tensor([ 0, 12, 49, 66, 58, 39, 72]) the targer: 9
when the input is tensor([ 0, 12, 49, 66, 58, 39, 72,  9]) the targer: 2
when the input is tensor([ 0, 12, 49, 66, 58, 39, 72,  9,  2]) the targer: 25


In [16]:
import torch

# Set random seed for reproducibility
torch.manual_seed(1337)

# Sample data for train_data and val_data (as placeholders)
#train_data = torch.arange(100)  # This is just an example: A sequence of numbers from 0 to 99
#val_data = torch.arange(100, 120)  # Example validation data

batch_size = 6
block_size = 10

def get_batch(split):
    data = train_data if split == "train" else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))  # Random indices for batch creation
    x = torch.stack([data[i:i + block_size] for i in ix])  # Inputs (x)
    y = torch.stack([data[i + 1:i + block_size + 1] for i in ix])  # Targets (y)
    return x, y

# Get a batch for training
xb, yb = get_batch('train')

print('inputs:')
print(xb.shape)
print(xb)
print('targets:')
print(yb.shape)
print(yb)

# Iterating over the batch
for b in range(batch_size):
    for t in range(block_size):
        context = xb[b, :t+1]  # Input context (all values till the current position)
        target = yb[b, t]  # Target (next value after the context)
        print(f"when input is {context.tolist()} the target : {target.item()}")


inputs:
torch.Size([6, 10])
tensor([[ 2, 25, 52,  2, 78, 50, 64, 44,  2, 46],
        [46, 37, 61,  2, 52, 60, 40, 62,  2,  2],
        [59, 25, 40, 69,  2, 60, 70,  9,  0, 52],
        [64,  2, 51, 60,  2, 25, 63,  2, 25, 63],
        [44, 62,  2, 30, 62, 60, 40, 69,  0, 11],
        [ 2, 46, 66, 31,  2, 54, 69, 44, 62,  2]])
targets:
torch.Size([6, 10])
tensor([[25, 52,  2, 78, 50, 64, 44,  2, 46, 52],
        [37, 61,  2, 52, 60, 40, 62,  2,  2, 32],
        [25, 40, 69,  2, 60, 70,  9,  0, 52, 63],
        [ 2, 51, 60,  2, 25, 63,  2, 25, 63, 59],
        [62,  2, 30, 62, 60, 40, 69,  0, 11, 54],
        [46, 66, 31,  2, 54, 69, 44, 62,  2, 30]])
when input is [2] the target : 25
when input is [2, 25] the target : 52
when input is [2, 25, 52] the target : 2
when input is [2, 25, 52, 2] the target : 78
when input is [2, 25, 52, 2, 78] the target : 50
when input is [2, 25, 52, 2, 78, 50] the target : 64
when input is [2, 25, 52, 2, 78, 50, 64] the target : 44
when input is [2, 25, 52

In [17]:
print(xb)

tensor([[ 2, 25, 52,  2, 78, 50, 64, 44,  2, 46],
        [46, 37, 61,  2, 52, 60, 40, 62,  2,  2],
        [59, 25, 40, 69,  2, 60, 70,  9,  0, 52],
        [64,  2, 51, 60,  2, 25, 63,  2, 25, 63],
        [44, 62,  2, 30, 62, 60, 40, 69,  0, 11],
        [ 2, 46, 66, 31,  2, 54, 69, 44, 62,  2]])
